[package]
name = "closure"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ast = { path = "../ast" }
ty = { path = "../ty" }
util = { path = "../util" }
log = "0.4.0"
anyhow = "1.0"
id-arena = "2"